Feature/rbac on collection ids
akto-api-security/akto pull request #1296
Opened 2024-07-22 17:50 UTC by TangoBeee

2024-07-24 14:54 UTC, Ark2307 requested changes

2024-07-24 14:54 UTC, Ark2307 commented on apps/dashboard/src/main/java/com/akto/action/observe/InventoryAction.java
> +            List<Integer> collectionIds = UsersCollectionsList.getCollectionsIdForUser(Context.userId.get(), Context.accountId.get());
take common items here also

2024-07-24 14:54 UTC, Ark2307 commented on apps/dashboard/src/main/java/com/akto/utils/RiskScoreOfCollections.java
> +        List<Integer> collectionIds = UsersCollectionsList.getCollectionsIdForUser(Context.userId.get(), Context.accountId.get());
remove from here

2024-07-24 14:54 UTC, Ark2307 commented on libs/dao/src/main/java/com/akto/dao/ApiCollectionsDao.java
> +        if(collectionIds != null && !collectionIds.isEmpty()) {
not needed here as well

2024-07-24 14:54 UTC, Ark2307 commented on libs/dao/src/main/java/com/akto/dao/FilterSampleDataDao.java
> +        return TestingEndpoints.getFilterPrefix(ApiCollectionUsers.CollectionType.Id_ApiInfoKey_ApiCollectionId) + ApiInfo.ApiInfoKey.API_COLLECTION_ID;
confirm this once

2024-07-25 11:06 UTC, TangoBeee commented on apps/dashboard/src/main/java/com/akto/action/ApiCollectionsAction.java
> +            if(collectionIds != null && !collectionIds.isEmpty()) {
> what you have access to

I didn't get this.

2024-07-25 11:06 UTC, TangoBeee commented on apps/dashboard/src/main/java/com/akto/action/ApiCollectionsAction.java
>          for(Map.Entry<String, List<Integer>> entry : userCollectionMap.entrySet()) {
How do I convert a list to a set in a loop?

2024-11-27 09:31 UTC, merged