Feature/onboarding
akto-api-security/akto pull request #198
Opened 2023-03-14 15:58 UTC by avneesh-akto

2023-03-16 09:27 UTC, aktoboy requested changes

2023-03-16 09:27 UTC, aktoboy commented on apps/dashboard/src/main/java/com/akto/listener/RuntimeListener.java
> +        // todo: skipKafka = true for onPrem also
Do we need to handle this TODO?

2023-03-16 09:27 UTC, aktoboy commented on apps/dashboard/src/main/java/com/akto/listener/RuntimeListener.java
> +        AuthMechanismsDao.instance.insertOne(authMechanism);
Once the demo collection's testing is executed, we will also need to delete these tokens, right?

2023-03-16 09:27 UTC, aktoboy commented on apps/dashboard/src/main/java/com/akto/listener/RuntimeListener.java
> +            initialiseDemoCollections();
What will happen to user onboarding if there is an exception here?

2023-03-16 09:27 UTC, aktoboy commented on apps/dashboard/web/src/apps/dashboard/views/testing/components/TestingRunResults.vue
> +                ["Looking for love in all the wrong places", "../../etc/pwd"],
Jokes were supposed to be maintained in a seperate file, right?

2023-03-16 09:27 UTC, aktoboy commented on apps/dashboard/web/src/apps/dashboard/views/testing/components/TestingRunResults.vue
> +            return api.fetchTestingRunResultSummaries(this.startTimestamp, this.endTimestamp, this.testingRunHexId).then(resp => {
typo?

2023-03-17 10:44 UTC, avneesh-akto commented on apps/dashboard/src/main/java/com/akto/listener/RuntimeListener.java
> +        // todo: skipKafka = true for onPrem also
no

2023-03-17 11:21 UTC, merged